### ISSUE TITLE
require HTML::Entities on WIndows fails with Error: HTML::Parser object version 3.69 does not match bootstrap parameter 3.71

### ISSUE THREAD

**Issue by kberov** [gisle/html-parser#8]
I think in HTML::Entities the version should be changed to 3.71 to mach the Version of HTML::Parser.
Now Text::MultiMarkdown fails to build on Windows because of this error.
Here is the build log:
http://ppm4.activestate.com/MSWin32-x86/5.16/1600/B/BO/BOBTFISH/Text-MultiMarkdown-1.000035.d/log-20140720T030537.txt

https://github.com/gisle/html-parser/blob/master/lib/HTML/Entities.pm#L149

Thanks and Regards!

**Comment by gisle** [comment]
You have a broken installation.  The fact that `HTML::Entites` have a `$VERSION` that's older should not matter.  Try to reinstall `HTML-Parser`.
